/* demo_convert_options.h */

/* File autogenerated by gengetopt version 2.1  */

#ifndef _demo_convert_options_h
#define _demo_convert_options_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct gengetopt_args_info {
  int v1tag_flag;	/* Render only the id3v1 tag (default=off).  */
  int v2tag_flag;	/* Render only the id3v2 tag (default=off).  */
  int strip_flag;	/* Strip the tags instead of rendering (default=off).  */
  int padding_flag;	/* Use padding in the tag (default=off).  */
  int warning_flag;	/* Turn on warnings (for debugging) (default=off).  */
  int notice_flag;	/* Turn on notices (for debugging) (default=off).  */

  int help_given ;	/* Wheter help was given.  */
  int version_given ;	/* Wheter version was given.  */
  int v1tag_given ;	/* Whether v1tag was given.  */
  int v2tag_given ;	/* Whether v2tag was given.  */
  int strip_given ;	/* Whether strip was given.  */
  int padding_given ;	/* Whether padding was given.  */
  int warning_given ;	/* Whether warning was given.  */
  int notice_given ;	/* Whether notice was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _demo_convert_options_h */
