/* demo_tag_options.h */

/* File autogenerated by gengetopt version 2.1  */

#ifndef _demo_tag_options_h
#define _demo_tag_options_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct gengetopt_args_info {
  int v1tag_flag;	/* Render only the id3v1 tag (default=off).  */
  int v2tag_flag;	/* Render only the id3v2 tag (default=off).  */
  char * artist_arg;	/* Set the artist information.  */
  char * album_arg;	/* Set the album title information.  */
  char * song_arg;	/* Set the title information.  */
  char * comment_arg;	/* Set the comment information.  */
  char * desc_arg;	/* Set the comment description.  */
  char * year_arg;	/* Set the year.  */
  char * track_arg;	/* Set the track number.  */
  char * total_arg;	/* Set the total number of tracks.  */
  short genre_arg;	/* Set the genre.  */
  int warning_flag;	/* Turn on warnings (for debugging) (default=off).  */
  int notice_flag;	/* Turn on notices (for debugging) (default=off).  */

  int help_given ;	/* Wheter help was given.  */
  int version_given ;	/* Wheter version was given.  */
  int v1tag_given ;	/* Whether v1tag was given.  */
  int v2tag_given ;	/* Whether v2tag was given.  */
  int artist_given ;	/* Whether artist was given.  */
  int album_given ;	/* Whether album was given.  */
  int song_given ;	/* Whether song was given.  */
  int comment_given ;	/* Whether comment was given.  */
  int desc_given ;	/* Whether desc was given.  */
  int year_given ;	/* Whether year was given.  */
  int track_given ;	/* Whether track was given.  */
  int total_given ;	/* Whether total was given.  */
  int genre_given ;	/* Whether genre was given.  */
  int warning_given ;	/* Whether warning was given.  */
  int notice_given ;	/* Whether notice was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _demo_tag_options_h */
